DEVICE_IP = "192.168.0.172"
USERNAME = "admin"
PASSWORD = ""
WUI_ADMIN_URL = "http://" + USERNAME + ":" + PASSWORD + "@" + DEVICE_IP + "/admin"
CLOUD_URL = "https://staging.epiphan.cloud/"
CLOUD_USERNAME = "victoria.mosyondz@actimind.com"
CLOUD_PASSWORD = "BaryaLives4Mira"